# Generated by Django 5.0.4 on 2024-05-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrappedDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('words_collection', models.TextField()),
                ('unique_words_count', models.IntegerField()),
                ('total_words_count', models.IntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('total_reviews', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
